name: flutter_template
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  auto_route:
  flutter:
    sdk: flutter
  flutter_hooks:
  hooks_riverpod:
  json_annotation: 
  path:
  path_provider:
  riverpod_annotation:
  sembast:
  uuid:
  freezed_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  riverpod_generator:
  build_runner:
  custom_lint:
  riverpod_lint:
  auto_route_generator:
  json_serializable:
  freezed:

flutter:
  uses-material-design: true


