name: todo_easy_riverpod_architecture
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  auto_route: ^7.8.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.10
  json_annotation: ^4.8.1
  path: ^1.8.3
  path_provider: ^2.1.2
  riverpod_annotation: ^2.3.4
  sembast: ^3.6.0
  uuid: ^4.3.3
  freezed_annotation: ^2.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.9
  auto_route_generator: ^7.3.2
  json_serializable: ^6.7.1
  freezed: ^2.4.7

flutter:
  uses-material-design: true


